updated remote_zpool to only import cached pools

diff --git a/rc.d/remote_zpool b/rc.d/remote_zpool
--- a/rc.d/remote_zpool
+++ b/rc.d/remote_zpool
@@ -2,20 +2,36 @@
 #
 #
 
-# PROVIDE: remote_zpool
-# REQUIRE:iscsictl
-# BEFORE:  DAEMON
+# PROVIDE: remotte_zpool
+# REQUIRE: iscsictl
+# 
 # KEYWORD: nojail
 
 . /etc/rc.subr
 
 name="remote_zpool"
-desc="mount ISCSI connected zpools"
+desc="Import ISCSI attached ZPOOLs"
 rcvar="remote_zpool_enable"
-command="/sbin/zpool"
+start_cmd="zpool_start"
+required_modules="zfs"
 
-command_args="import -a"
-required_modules="iscsi zfs"
+zpool_start()
+{
+	local cachefile
+
+	for cachefile in /etc/zfs/zpool.cache /boot/zfs/zpool.cache; do
+		if [ -r $cachefile ]; then
+			zpool import -c $cachefile -a -N
+			if [ $? -ne 0 ]; then
+				echo "Import of zpool cache ${cachefile} failed," \
+				    "will retry after root mount hold release"
+				root_hold_wait
+				zpool import -c $cachefile -a -N
+			fi
+			break
+		fi
+	done
+}
 
 load_rc_config $name
 run_rc_command "$1"
